version: 2.1

jobs:
  run_script:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install requests pandas blomp-api
      - run:
          name: Run json.py Script
          environment:
            MAIL: $MAIL
            PASSWORD: $PASSWORD
          command: python json.py

workflows:
  version: 2
  scheduled_workflow:
    triggers:
      - schedule:
          cron: "*/5 * * * *"
          filters:
            branches:
              only: main
    jobs:
      - run_script
